config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "posts#index"
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'html_css' => 'posts#html_css'
  get 'html_css/:id' => 'posts#show', as: 'html_css_show'
  get 'javascript' => 'posts#javascript'
  get 'javascript/:id' => 'posts#show', as: 'javascript_show'
  get 'ruby' => 'posts#ruby'
  get 'ruby/:id' => 'posts#show', as: 'ruby_show'
  get 'void' => 'posts#void'
  get 'void/:id' => 'posts#show', as: 'void_show'
  get '/about', to: 'pages#about'
  get '/markdown', to: 'pages#markdown'
  
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all # The "match" method is used to match a URL to one or more routes. It’s a bit more flexible than for instance the "get" method because you can configure it to be triggered in conjunction with any matching route and HTTP method as opposed to for instance just a route matching the get method. You can pass specific HTTP methods into the via option, however we want to match routes in conjunction with any HTTP method, and so I’ve passed all into via.
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  
  resources :activities
  resources :users
  get '/users/(:comment)', to: 'users#show', as: 'autor'
  
  resources :posts do
    collection do
      put 'approve/:id', to: 'posts#approve', as: :approve
      put 'unapprove/:id', to: 'posts#unapprove', as: :unapprove
    end
    member do
      put 'like', to: 'posts#upvote'
      put 'dislike', to: 'posts#downvote'
    end
    get :autocomplete_tag_name, :on => :collection
    get :autocomplete_post_title, :on => :collection
    resources :comments do
      resources :comments
    end
  end
  
  get '/posts/:id', to: 'posts#show', as: 'comment_post'
  get '/posts/:post_id/comments/:id', to: 'comments#show', as: 'comment_reply'
  get '/posts/:post_id/comments/:comment_id/comments/:id', to: 'comments#show', as: 'comment_reply_reply'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
  apply_simple_captcha
  belongs_to :user
  belongs_to :post
  belongs_to :commentable, :polymorphic => true # belongs_to :post
  has_many :comments, :as => :commentable, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 55 }
  validates :body, presence: true, length: { minimum: 6, maximum: 2000 }
  
  def post
    return @post if defined?(@post)
    @post = commentable.is_a?(Post) ? commentable : commentable.post
  end
  
  def content
    MarkdownService.new.render(body).html_safe
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :get_parent

  def index
    @post = Post.friendly.find(params[:post_id])
    @comments = @post.comments.all
  end

  def new
    @post = Post.friendly.find(params[:post_id])
    @comment = @parent.comments.create
  end

  def show
    @post = Post.friendly.find(params[:post_id])
    @comment = @parent.comments.find(params[:id])
  end

  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @parent.comments.create
    if simple_captcha_valid? || logged_in? && current_user
      @comment = @parent.comments.create(comment_params)
      redirect_to post_path(@comment.post)
      flash[:success] = "Comment successfully created!"
    else
      redirect_to @post
      flash[:danger] = "Invalid Captcha!"
    end
  end

  def edit
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find(params[:comment_id]) if params[:comment_id] # Reply
    @comment = Comment.find(params[:id]) if params[:id] # Comment
  end

  def update
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find(params[:comment_id]) if params[:comment_id] # Reply
    @comment = Comment.find(params[:id]) if params[:id] # Comment
    if @comment.update_attributes(comment_params)
      redirect_to post_path(@comment.post)
      flash[:success] = "Comment successfully updated!"
    else
      render 'edit'
      flash[:danger] = "Oops!! Errors found!! Comment can't be updated!"
    end
  end

  def destroy
    @post = Post.friendly.find(params[:post_id]) # Redirect back to post
    @comment = Comment.find(params[:comment_id]) if params[:comment_id] # Reply
    @comment = Comment.find(params[:id]) if params[:id] # Comment
    if @comment.destroy
      redirect_to post_path(@post)
      flash[:success] = "Comment successful deleted!"
    else
      flash[:danger] = "Oops!! Errors found!! Comment can't be delete!"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body, :parent_id, :captcha, :captcha_key)
  end

  def get_parent
    @parent = Post.friendly.find(params[:post_id]) if params[:post_id]
    @parent = Comment.find(params[:comment_id]) if params[:comment_id]
    redirect_to root_path unless defined?(@parent)
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @comment = Comment.find(params[:id])
    redirect_to(root_url) unless logged_in? && (current_user.admin? || @comment.name == current_user.name)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
  <% if comment.parent_id %>
      <%= link_to autor_path(comment.parent_id) do %>
        <p class="comment-logo"><%= image_tag "logo.png", width: '48px', height: '48px', alt: 'Avatar ' + comment.name %></p>
      <% end %>
    <% else %>
      <p class="comment-logo"><%= image_tag "logo.png", width: '48px', height: '48px', alt: 'Avatar ' + comment.name %></p>
  <% end %>
              
  <div class="comment-block">
      <div class="comment-wrap-info"><!--Content -->
        <p class="comment-single"><!-- Comment Single -->
          <% from_reply_form ||= nil %>
          <% unless from_reply_form %>
            <%= link_to '#'+comment.id.to_s, post_comment_path(@post, comment) %>
          <% end %>
        </p>
        <% if comment.parent_id %><!-- Comment Name -->
          <%= link_to comment.name, autor_path(comment.parent_id) %>
        <% else %>
          <%= comment.name %>
        <% end %>
         <p class="comment-time">commented on <%= l(comment.created_at, format: '%d %B %Y') %></p><!-- Comment Time -->
        <%# l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %> <!--Comment Date: 23 december, 21:36:33-->
        <p class="reply-comment"><%= link_to 'Reply', new_post_comment_comment_path(@post, comment) %></p> <!-- Comment Reply -->
        <% if is_an_admin? || logged_in? && comment.name == current_user.name %><!-- Comment Edit -->
          | <p class="edit-comment"><%= link_to 'Edit', edit_post_comment_path(@post, comment) %></p>
        <% end %>
        <% if comment.name == @post.user.name %>
          <p class="author-comment">Owner</p>
        <% end %>
      </div>

    <div class="comment-body"><%= comment.content %><!-- Body Comment -->
      <% unless comment.comments.empty? %>
      <ul class="comment-list">
        <%= render :partial => 'comments/comment_comments', :collection => comment.comments, :as => :comment %>
      </ul>
    <% end %>
    </div>
    <% if logged_in? && current_user.admin? %>
      <p class="comment-delete"><%= link_to 'Delete', post_comment_path(@post, comment),
                    method: :delete,
                    class: "button-delete",
                    data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
  </div>

app/views/comments/_comment_comments.html.erb
<div class="comment-block-reply">
  <div class="comment clearfix">
    <div class="comment-content-reply"><!--Content -->
      <p class="comment-name-reply"><%= image_tag "logo.png", width: '20px', height: '20px', style: 'margin-right: 5px' %><%= comment.name %>
      
      <p class="comment-time-reply">commented on <%= l(comment.created_at, format: '%d %B %Y') %></p>
      <!--<p><%# l(comment.created_at, format: '%B, %d %Y %H:%M:%S') %></p> Comment Date: 23 december, 21:36:33-->
      <% if is_an_admin? || logged_in? && comment.name == current_user.name %>
        <p class="edit-comment-reply"><%= link_to 'Edit', edit_post_comment_comment_path(@post, comment, comment.id) %></p>
      <% end %>
      <% if comment.name == @post.user.name %>
        <p class="author-comment-reply">Owner</p>
      <% end %>
    </div>
  </div>

  <div class="comment-body-reply"><%= comment.content %><!-- Body Comment -->
  </div>
  <% if logged_in? && current_user.admin? %>
    <p class="comment-reply"><%= link_to 'x', post_comment_comment_path(@post, comment, comment.id),
                  method: :delete,
                  class: "button-reply",
                  data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= link_to 'Back to Post', post_path(@comment.post) %>
<h1>New reply comment: </h1>
<%= render 'comments/reply_comment' %>

<%= form_for [@post, @parent, @comment] do |f| %>
  <% if logged_in? && current_user %>
    <%= f.hidden_field :name, :value => current_user.name %>
    <%= f.hidden_field :parent_id, :value => @post.id %>
    <div class="label-body"><%= f.label 'Message' %></div>
    <div class="text-body"><%= f.text_area :body, placeholder: 'Minimum 6 characters' %></div>
    <%= f.submit %>
    <% else %>
    <div class="label-name"><%= f.label 'Your Name' %></div>
    <div class="text-name"><%= f.text_field :name, autofocus: true %></div>
    <div class="label-body"><%= f.label :body %></div>
    <div class="text-body"><%= f.text_area :body %></div>
    <%= show_simple_captcha %><br />
    <%= f.submit %>
  <% end %>
<% end %>

app/views/comments/_form_comments.html.erb
<h3>Add a comment:</h3>
      <span class="md-page">Markdown is <%= link_to 'allowed', markdown_path, target: '_blank', rel: 'nofollow' %></span>
      <%= form_for([@post, @post.comments.build]) do |f| %>
        <% if logged_in? && current_user %>
          <%= f.hidden_field :name, :value => current_user.name %>
          <%= f.hidden_field :parent_id, :value => current_user.id %>
          <div class="label-body"><%= f.label 'Message' %></div>
          <div class="text-body"><%= f.text_area :body, placeholder: 'Minimum 6 characters' %></div>
          <%= f.submit %>
          <% else %>
          <div class="label-name"><%= f.label 'Your Name' %></div>
          <div class="text-name"><%= f.text_field :name, placeholder: 'Minimum 3 characters' %></div>
          <div class="label-body"><%= f.label 'Message' %></div>
          <div class="text-body"><%= f.text_area :body, placeholder: 'Minimum 6 characters' %></div>
          <%= show_simple_captcha %><br />
          <%= f.submit %>
        <% end %>
      <% end %>
      
      

app/views/comments/_reply_comment.html.erb
<% if @comment.commentable_id %>
<p class="comment-logo"><%= image_tag "logo.png", width: '48px', height: '48px', alt: 'Avatar ' + @parent.name %>
  <div class="comment-block">
  <div class="comment-wrap-info"><!--Content -->
      <% if @parent.parent_id %><!-- Comment Name -->
          <%= link_to @parent.name, autor_path(@parent.parent_id) %>
        <% else %>
          <%= @parent.name %>
        <% end %>
      <p class="comment-time"><%= time_ago_in_words(@parent.created_at) %> Ago</p>
  </div>
  <div class="comment-body"><%= @parent.content %><!-- Body Comment -->
  </div>
</div>
<% end %>

app/views/comments/edit.html.erb
<%= link_to 'Back', post_path(@comment.post) %>
<h1>Edit Post</h1>
<% if current_page?(edit_post_comment_path) %>

<%= form_for([@post, @comment]) do |f| %>
  <div class="label-name"><%= f.label 'Your Name' %></div>
  <div class="text-name"><%= f.text_field :name %></div>
  <div class="label-body"><%= f.label :body %></div>
  <div class="text-body"><%= f.text_area :body %></div>
  <%= f.submit %>
<% end %>

<% elsif current_page?(edit_post_comment_comment_path) %>
<%= form_for [@post, @parent, @comment] do |f| %><!-- Form for Reply Comment -->
  <div class="label-name"><%= f.label 'Your Name' %></div>
  <div class="text-name"><%= f.text_field :name, autofocus: true %></div>
  <div class="label-body"><%= f.label :body %></div>
  <div class="text-body"><%= f.text_area :body %></div>
  <%= f.submit %>
<% end %>
<% end %>

app/views/comments/index.html.erb
<h1>Join the discussion</h1>
<p>Click the button below to start a new thread:</p>
<p>
  <%= link_to 'Add new topic', new_comment_path %>
</p>
<%= render @comments %>

app/views/comments/new.html.erb
<% if current_page?(new_post_comment_path) %>
<%= render 'comments/form_comments' %><!-- Form for Comment Post -->
<% elsif current_page?(new_post_comment_comment_path) %>
<%= render 'comments/form' %><!-- Form for Reply Comment -->
<% end %>

app/views/comments/show.html.erb
<%= link_to 'Back to Post', post_path(@comment.post) %>
<h1>Comment</h1>
<% if @comment %>
  <%= render 'comment', comment: @comment, from_reply_form: true %>
<% end %>