config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "posts#index"
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'html_css' => 'posts#html_css'
  get 'html_css/:id' => 'posts#show', as: 'html_css_show'
  get 'javascript' => 'posts#javascript'
  get 'javascript/:id' => 'posts#show', as: 'javascript_show'
  get 'ruby' => 'posts#ruby'
  get 'ruby/:id' => 'posts#show', as: 'ruby_show'
  get 'void' => 'posts#void'
  get 'void/:id' => 'posts#show', as: 'void_show'
  get '/about', to: 'pages#about'
  get '/markdown', to: 'pages#markdown'
  
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all # The "match" method is used to match a URL to one or more routes. It’s a bit more flexible than for instance the "get" method because you can configure it to be triggered in conjunction with any matching route and HTTP method as opposed to for instance just a route matching the get method. You can pass specific HTTP methods into the via option, however we want to match routes in conjunction with any HTTP method, and so I’ve passed all into via.
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  
  resources :activities
  resources :users
  get '/users/(:comment)', to: 'users#show', as: 'autor'
  
  resources :posts do
    collection do
      put 'approve/:id', to: 'posts#approve', as: :approve
      put 'unapprove/:id', to: 'posts#unapprove', as: :unapprove
    end
    member do
      put 'like', to: 'posts#upvote'
      put 'dislike', to: 'posts#downvote'
    end
    get :autocomplete_tag_name, :on => :collection
    get :autocomplete_post_title, :on => :collection
    resources :comments do
      resources :comments
    end
  end
  
  get '/posts/:id', to: 'posts#show', as: 'comment_post'
  get '/posts/:post_id/comments/:id', to: 'comments#show', as: 'comment_reply'
  get '/posts/:post_id/comments/:comment_id/comments/:id', to: 'comments#show', as: 'comment_reply_reply'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user } if !defined?(Rails::Console) # NOT in rails console
  acts_as_votable
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]
  belongs_to :user
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  validates :categories, presence: true, :inclusion => { :in => ['The Void', 'HTML + CSS','Javascript','Ruby'] }
  validates :featured_post, presence: true, :inclusion => { :in => ['yes', 'no'] }
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 75 }
  validates :body, presence: true, length: { minimum: 10 }
  validates :all_tags, presence: true, length: { minimum: 2, maximum: 15 }, 
  :length => { # Maximum 5 words
  :maximum => 5, # Maximum 5 words
  :tokenizer => lambda { |str| str.scan(/\w+/) },
  :too_long  => "Please limit your summary to %{count} words"
}
  scope :featured, -> { where(featured_post: 'yes').order(created_at: :desc).limit(100) }
  scope :unfeatured, -> { where(featured_post: 'no').order(created_at: :desc).limit(100) }
  scope :approved, -> { where status: 'approved' }
  scope :draft, -> { where status: 'draft' }
  
  def slug_candidates
    [
      :title,
      [:title, :id] # Take cares of duplicate titles
    ]
  end
  
  def self.search(query)
    if Rails.env.production?
      where("CAST(title as text) ilike ? OR CAST(id AS text) ilike ? OR CAST(categories AS text) ilike ?", "%#{query}%", "%#{query}%", "%#{query}%") # postgres
    else
      where("title like ? OR id like ? OR categories like ?", "%#{query}%", "%#{query}%", "%#{query}%") # sqlite
    end
  end
  
  def content
    MarkdownService.new.render(body).html_safe
  end
  
  #Getter and Setter for all_tags vertial attribute
  def all_tags=(names)
    self.tags = names.split(" ").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(" ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  autocomplete :post, :title, :full => true
  autocomplete :tag, :name, :full => true # This will create an action autocomplete_tag_name on your controller, don't forget to add it on your routes file
  helper_method :index
  #before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  # Allow the current user to delete his OWN entry
  before_action :correct_user,   only: [:edit, :update, :destroy]
  # Allow admins to delete all entries
  #before_action :admin_user,     only: [:create, :edit, :update, :destroy]

  def index
    if params[:tag]
      @posts_featured = Post.tagged_with(params[:tag]).featured.approved
      @posts_unfeatured = Post.tagged_with(params[:tag]).unfeatured.approved
    elsif params[:search]
      @posts_featured = Post.search(params[:search]).featured.approved
      @posts_unfeatured = Post.search(params[:search]).unfeatured.approved
    else
      @posts_featured = Post.all.featured.approved
      @posts_unfeatured = Post.all.unfeatured.approved
    end
  end

  def new
    if is_an_admin? || logged_in? && current_user
      @post = Post.new
    else
      flash[:danger] = "Login or signup to create new post!"
      redirect_to login_path
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)
    if current_user.admin?
      @post.status = "approved"
    else
      @post.status = "draft"
    end
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.friendly.find(params[:id]) if current_user
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def upvote
    @post = Post.friendly.find(params[:id])
    if current_user
      respond_to do |format|
        unless current_user.voted_for? @post
          format.html { redirect_to @post }
          format.json { head :no_content }
          format.js { render :layout => false }
          @post.vote_total = @post.vote_total + 1
          @post.save
          @post.upvote_by current_user
        else
          flash[:danger] = 'You allready voted this entry'
          format.html { redirect_to @post }
          format.json { head :no_content }
          format.js
        end
      end
    else
      flash[:danger] = "You need to log in or sign up to vote!"
      redirect_to login_path
    end
  end

  def downvote
    @post = Post.friendly.find(params[:id])
    respond_to do |format|
      unless current_user.voted_for? @post
        format.html { redirect_to @post }
        format.json { head :no_content }
        format.js { render :layout => false }
        @post.vote_total = @post.vote_total + 1
        @post.save
        @post.downvote_by current_user
      else
        flash[:danger] = 'You allready voted this entry'
        format.html { redirect_to @post }
        format.json { head :no_content }
        format.js
      end
    end
  end

  def html_css
    #@posts = Post.all.order('created_at DESC').paginate(page: params[:page], :per_page => 10)
    @posts_featured = Post.all.featured
    @posts_unfeatured = Post.all.unfeatured
  end

  def javascript
    #@posts = Post.all.order('created_at DESC').paginate(page: params[:page], :per_page => 10)
    @posts_featured = Post.all.featured
    @posts_unfeatured = Post.all.unfeatured
  end

  def ruby
    #@posts = Post.all.order('created_at DESC').paginate(page: params[:page], :per_page => 10)
    @posts_featured = Post.all.featured
    @posts_unfeatured = Post.all.unfeatured
  end

  def void
    #@posts = Post.all.order('created_at DESC').paginate(page: params[:page], :per_page => 10)
    @posts_featured = Post.all.featured
    @posts_unfeatured = Post.all.unfeatured
  end

  def approve
    @post = Post.find(params[:id])
    @post.update_attributes({status: "approved"})
    redirect_to @post
  end

  def unapprove
    @post = Post.find(params[:id])
    @post.update_attributes({status: "draft"})
    redirect_to @post
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :categories, :featured_post, :all_tags, :status)
  end

  # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

  # Confirms the correct user.
  def correct_user
    @post = Post.friendly.find(params[:id])
    redirect_to(root_url) unless current_user?(@post.user) || logged_in? && current_user.admin?
  end

end

app/helpers/posts_helper.rb
module PostsHelper
  
  def tag_links(tags)
    tags.split(" ").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(" ") 
  end
  
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
  
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %><br>
  <%= f.autocomplete_field :title, autocomplete_post_title_posts_path, autofocus: 'autofocus' %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area(:body, class: 'bg-code') %><br>
  <%= f.label 'Tags (maximum 5)' %><br>
  <%= f.autocomplete_field :all_tags, autocomplete_tag_name_posts_path, 'data-delimiter' => ' ', input_html: { :multiple => true }, class: 'all-tags', placeholder: "Tags separated with comma" %>
  <%# f.text_field :all_tags, class: 'all-tags', placeholder: "Tags separated with comma" %>
  <div style="float: left; margin-right: 10px"><p><%= f.label :categories %><br>
  <%= f.select :categories, [ 'The Void', 'HTML + CSS', 'Javascript', 'Ruby' ], :prompt => 'Select One' %>
  </p></div>
  <%= f.label 'Featured Post?' %><br />
  <%= f.select :featured_post, [ 'no', 'yes' ], :default => 'no' %><br />
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/downvote.js.erb
$('.npos').bind('ajax:success', function() {
$('.ncount-<%= @post.id %>').html('<%=escape_javascript @post.get_downvotes.size.to_s %>');
});
$("#notice").html("<%= escape_javascript(render :partial => 'layouts/flash' , :locals => { :flash => flash }).html_safe %>");

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
  <%= render 'form' %>

app/views/posts/html_css.html.erb
    <% @posts_featured.each do |post| %>
    <article>
    <% if post.categories == 'HTML + CSS' %>
      <div class="post_wrapper <% if post.featured_post == 'yes' %>featured-post<% end %>">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), html_css_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', html_css_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    <% end %>
    
    <% @posts_unfeatured.each do |post| %>
    <article>
    <% if post.categories == 'HTML + CSS' %>
      <div class="post_wrapper">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), html_css_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', html_css_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    <% end %>

app/views/posts/index.html.erb
    <% @posts_featured.each do |post| %>
    <article>
    <% if post.categories == 'HTML + CSS' %>
      <div class="post_wrapper <% if post.featured_post == 'yes' %>featured-post<% end %>">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), html_css_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', html_css_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    
    <article>
      <% if post.categories == 'Javascript' %>
      <div class="post_wrapper <% if post.featured_post == 'yes' %>featured-post<% end %>">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), javascript_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', javascript_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    
    <article>
      <% if post.categories == 'Ruby' %>
      <div class="post_wrapper <% if post.featured_post == 'yes' %>featured-post<% end %>">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), ruby_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', ruby_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    
    <article>
      <% if post.categories == 'The Void' %>
      <div class="post_wrapper <% if post.featured_post == 'yes' %>featured-post<% end %>">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), void_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', void_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    <% end %>
    
    <% @posts_unfeatured.each do |post| %>
    <article>
    <% if post.categories == 'HTML + CSS' %>
      <div class="post_wrapper">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), html_css_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', html_css_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    
    <article>
      <% if post.categories == 'Javascript' %>
      <div class="post_wrapper">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), javascript_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', javascript_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    
    <article>
      <% if post.categories == 'Ruby' %>
      <div class="post_wrapper">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), ruby_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', ruby_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    
    <article>
      <% if post.categories == 'The Void' %>
      <div class="post_wrapper">
        <header><h2 class="title"><%= link_to highlight(post.title, params[:search]), void_show_path(post) %></h2></header>
        <div class="post-info">
          <span class="post-date">
            <span class="glyphicon glyphicon-calendar"></span>
            <%= post.created_at.strftime("%B %d, %Y") %>
          </span>
          <span class="post-author">
            <% if post.user_id %>
              <span class="glyphicon glyphicon-user"></span>
              <%= post.user.name %>
            <% end %>
          </span>
          <span class="post-category">
            <span class="glyphicon glyphicon-pencil"></span>
            Category: <strong><%= post.categories %></strong>
          </span>
          <span class="post-tags">
            <span class="glyphicon glyphicon-tags"></span>
            tags: <%= raw tag_links(post.all_tags) %>
          </span>
        </div>
        <div class="post-content-short">
          <%= highlight(post.content, params[:search]) %>
        </div>
        <%= link_to 'Continue Reading', void_show_path(post), class: 'btn-green' %>
      </div>
      <% end %>
    </article>
    <% end %>
    
    
    <!--<div class="tags-cloud glassy-bg">
      <h4>Tags Cloud</h4>
      <%# tag_cloud Tag.counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
        <%# link_to tag.name, tag_path(tag.name), class: css_class %>
      <%# end %>
    </div>-->

app/views/posts/new.html.erb
<h1>New Post</h1>
  <%= render 'form' %>

app/views/posts/show.html.erb
    <% provide(:title, @post.title ) %>
    <article role="article-post" <% if @post.status == "draft" %>class="unapproved"<% end %>>
      <header>
        <h1 class="title-show"><!-- Title -->
          <%= @post.title %>
        </h1>
      </header>
      <div class="date-show"><!-- Date -->
        Submitted <%= time_ago_in_words(@post.created_at) %> ago
        <% if is_an_admin? || logged_in? && post_author %>
        | <%= link_to 'Edit', edit_post_path(@post) %>
        | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <div class="category-show">
        Category: <strong><%= @post.categories %></strong>
      </div>
      <!-- BODY -->
      <div class="body">
        <%= @post.content %>
        <% if @post.status == "approved" %> <!-- Hide social and votes -->
          <aside class="vote-count bind-<%= @post.id %>">
            <!-- Positive Votes -->
            <%= link_to like_post_path(@post), method: :put, class: 'vpos' do %>
              <span class="glyphicon glyphicon-chevron-up"></span>
              <span class="vcount vcount-<%= @post.id %>"><%= @post.get_upvotes.size %></span>
            <% end %>
            <!-- Negative Votes -->
            <%= link_to dislike_post_path(@post), method: :put, class: 'npos' do %>
              <span class="glyphicon glyphicon-chevron-down"></span>
              <span class="ncount ncount-<%= @post.id %>"><%= @post.get_downvotes.size %></span>
            <% end %>
          </aside>
        
          <div class="social-share">
            <p class="twitter-btn">
              <a href="https://twitter.com/share" class="twitter-share-button" data-via="smironescu">Tweet</a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </p>
            <p class="facebook-btn">
              <div id="fb-root"></div>
                <script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&appId=117488980696&version=v2.0";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                
                <div class="fb-like" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
            </p>
            <p class="linkedin-btn">
              <script src="//platform.linkedin.com/in.js" type="text/javascript">
              lang: en_US
              </script>
              <script type="IN/Share" data-counter="right"></script>
            </p>
          </div>
        </div>
      <% end %>
      
      <div class="tags-show-post">Tags: <%= raw tag_links(@post.all_tags) %></div>
      <%# link_to 'Add a Comment', new_post_comment_path(@post) %>
    </article>
    
    <% if @post.status == "approved" %><!-- Hide Comments for unapproved posts -->
      <aside role="comments-post">
        <div id="comments">
          <!--<h2 class="comment-count"><%# pluralize(@post.comments.count, "Comment") %></h2>-->
          <ul class="comment_list"><!-- Render Partial List Comments -->
          <%= render :partial => 'comments/comment', :collection => @post.comments %>
          </ul>
          <%= render "comments/form_comments" %>
        </div>
      </aside>
    <% end %>

app/views/posts/upvote.js.erb
$('.vpos').bind('ajax:success', function() {
$('.vcount-<%= @post.id %>').html('<%=escape_javascript @post.get_upvotes.size.to_s %>');
});
$("#notice").html("<%= escape_javascript(render :partial => 'layouts/flash' , :locals => { :flash => flash }).html_safe %>");