config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "posts#index"
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'html_css' => 'posts#html_css'
  get 'html_css/:id' => 'posts#show', as: 'html_css_show'
  get 'javascript' => 'posts#javascript'
  get 'javascript/:id' => 'posts#show', as: 'javascript_show'
  get 'ruby' => 'posts#ruby'
  get 'ruby/:id' => 'posts#show', as: 'ruby_show'
  get 'void' => 'posts#void'
  get 'void/:id' => 'posts#show', as: 'void_show'
  get '/about', to: 'pages#about'
  get '/markdown', to: 'pages#markdown'
  
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all # The "match" method is used to match a URL to one or more routes. It’s a bit more flexible than for instance the "get" method because you can configure it to be triggered in conjunction with any matching route and HTTP method as opposed to for instance just a route matching the get method. You can pass specific HTTP methods into the via option, however we want to match routes in conjunction with any HTTP method, and so I’ve passed all into via.
  
  get 'tags/:tag', to: 'posts#index', as: "tag"
  
  resources :activities
  resources :users
  get '/users/(:comment)', to: 'users#show', as: 'autor'
  
  resources :posts do
    collection do
      put 'approve/:id', to: 'posts#approve', as: :approve
      put 'unapprove/:id', to: 'posts#unapprove', as: :unapprove
    end
    member do
      put 'like', to: 'posts#upvote'
      put 'dislike', to: 'posts#downvote'
    end
    get :autocomplete_tag_name, :on => :collection
    get :autocomplete_post_title, :on => :collection
    resources :comments do
      resources :comments
    end
  end
  
  get '/posts/:id', to: 'posts#show', as: 'comment_post'
  get '/posts/:post_id/comments/:id', to: 'comments#show', as: 'comment_reply'
  get '/posts/:post_id/comments/:comment_id/comments/:id', to: 'comments#show', as: 'comment_reply_reply'
  
end

app/views/layouts/_header.html.erb
  <header id="header" role="banner">
    <!-- ================= Mobile ======== -->
    <div id="logo-mobile">
      <%= link_to root_path do %><%= image_tag "logo.png", width: '50px', height: '50px' %><% end %>
    </div>
    <% if logged_in? %>
    <div class="buttons-mobile">
      <%= link_to new_post_path do %><button class="button">New Post</button><% end %>
      <%= link_to logout_path, method: :delete do %><button class="button">Log Out</button><% end %>
    </div>
    <% else %>
    <div class="buttons-mobile">
      <%= link_to signup_path do %><button class="button">Sign Up</button><% end %>
      <%= link_to login_path do %><button class="button">Log In</button><% end %>
    </div>
    <% end %>
    <div class="mobile-button">
      <span class="glyphicon glyphicon-tasks"></span>
    </div>
    <div class="mobile-menu">
        <ul>
          <li>
            <%= link_to 'HTML+CSS', html_css_path %>
          </li>
          <li>
            <%= link_to 'Javascript', javascript_path %>
          </li>
          <li>
            <%= link_to 'Ruby', ruby_path %>
          </li>
          <li>
            <%= link_to 'Void', void_path %>
          </li>
          <% if logged_in? %>
              <li>
                <%= link_to "Profile", current_user %>
              </li>
              <li>
                <%= link_to "Settings", edit_user_path(current_user) %>
              </li>
          <% end %>
            <li>
              <%= link_to 'Live!', activities_path %>
            </li>
          <li>
            <%= form_tag(posts_path, :method => "get", class: "form-search-mobile") do %> <%= text_field_tag :search, params[:search], placeholder: "Search..." %> <%# button_tag "", :title => nil do %> <%# end %> <% end %>
          </li>
        </ul>
      </div>
    <!-- ================= Mobile ========= -->
    <nav>
      <ul class="search-nav-items">
        <li class="search-btn"><a href="#search" title="Search"><span class="glyphicon glyphicon-search"></span></a></li>
        <li class="form-search-item" style="display: none"><%= form_tag(posts_path, :method => "get", class: "form-search") do %> <%= text_field_tag :search, params[:search], class: "search-query", placeholder: "Search...", autofocus: 'autofocus', data: { autocomplete: autocomplete_post_title_posts_path } %> <%= button_tag "", class: 'btn-search', :title => nil do %> <i class="search-me"></i> <% end %> <% end %></li>
      </ul>
      <ul class="nav-items">
        <% if current_page?(html_css_path) %>
        <li><%= link_to 'HTML+CSS', html_css_path, class: 'active-html' %></li>
        <% else %>
        <li><%= link_to 'HTML+CSS', html_css_path, class: 'noactive-html' %></li>
        <% end %>
  
        <% if current_page?(javascript_path) %>
        <li><%= link_to 'Javascript', javascript_path, class: 'active-js' %></li>
        <% else %>
        <li><%= link_to 'Javascript', javascript_path, class: 'noactive-js' %></li>
        <% end %>
  
        <% if current_page?(ruby_path) %>
        <li><%= link_to 'Ruby', ruby_path, class: 'active-ruby' %></li>
        <% else %>
        <li><%= link_to 'Ruby', ruby_path, class: 'noactive-ruby' %></li>
        <% end %>
        
        <% if current_page?(void_path) %>
        <li><%= link_to 'Void', void_path, class: 'active-void' %></li>
        <% else %>
        <li><%= link_to 'Void', void_path, class: 'noactive-void' %></li>
        <% end %>
      </ul>
      
      <% if logged_in? %>
        <div class="buttons">
          <%= link_to new_post_path do %><button class="button">New Post</button><% end %>
          <%= link_to logout_path, method: :delete do %><button class="button">Log Out</button><% end %>
        </div>
      <% else %>
        <div class="buttons">
          <%= link_to signup_path do %><button class="button">Sign Up</button><% end %>
          <%= link_to login_path do %><button class="button">Log In</button><% end %>
        </div>
      <% end %>
    </nav>
  </header>

app/views/layouts/_ie9_fix.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
  <aside id="sidebar" role="main-menu">
    <div id="logo">
      <%= link_to root_path do %><%= image_tag "logo.png", width: '100px', height: '100px' %><% end %>
    </div>
    <nav class="sidebar-menu">
      <ul>
        <li class="category"><%= link_to 'Home', root_path %></li>
        <% if current_page?(root_url) %>
        <li><%= link_to 'All Posts', root_path, class: 'active-sb' %></li>
        <% else %>
        <li><%= link_to 'All Posts', root_path %></li>
        <% end %>
        <% if logged_in? %>
        <% if current_page?(user_path(current_user)) %>
        <li><%= link_to "Profile", current_user, class: 'active-sb' %></li>
        <% else %>
        <li><%= link_to "Profile", current_user %></li>
        <% end %>
        <% if current_page?(edit_user_path(current_user)) %>
        <li><%= link_to "Settings", edit_user_path(current_user), class: 'active-sb' %></li>
        <% else %>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <% end %>
        <% end %>
        <% if current_page?(about_url) %>
        <li><%= link_to "About Me", about_path, class: 'active-sb' %></li>
        <% else %>
        <li><%= link_to "About Me", about_path %></li>
        <% end %>
        <% if current_page?(activities_path) %>
        <li><%= link_to "Live!", activities_path, class: 'active-sb' %></li>
        <% else %>
        <li><%= link_to "Live!", activities_path %></li>
        <% end %>
      </ul>
      <ul class="items-iphone6">
        <li class="category">Categories</li>
        <% if current_page?(html_css_path) %>
        <li><%= link_to 'HTML+CSS', html_css_path, class: 'active-html' %></li>
        <% else %>
        <li><%= link_to 'HTML+CSS', html_css_path, class: 'noactive-html' %></li>
        <% end %>

        <% if current_page?(javascript_path) %>
        <li><%= link_to 'Javascript', javascript_path, class: 'active-js' %></li>
        <% else %>
        <li><%= link_to 'Javascript', javascript_path, class: 'noactive-js' %></li>
        <% end %>

        <% if current_page?(ruby_path) %>
        <li><%= link_to 'Ruby', ruby_path, class: 'active-ruby' %></li>
        <% else %>
        <li><%= link_to 'Ruby', ruby_path, class: 'noactive-ruby' %></li>
        <% end %>

        <% if current_page?(void_path) %>
        <li><%= link_to 'Void', void_path, class: 'active-void' %></li>
        <% else %>
        <li><%= link_to 'Void', void_path, class: 'noactive-void' %></li>
        <% end %>
      </ul>
      <ul>
        <li class="category">Social</li>
        <li><a href="https://twitter.com/smironescu" target="_blank">Twitter</a></li>
        <li><a href="https://github.com/xexiu" target="_blank">Github</a></li>
        <li><a href="https://es.linkedin.com/in/smironescu/" target="_blank">LinkedIn</a></li>
        <li><a href="mailto:sergiu.mironescu@gmail.com" target="_blank">Email Me</a></li>
      </ul>
    </nav>
    <div class="copyright">&copy Copyright <%= Time.now.year %></div>
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= base_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes" />
  <meta name="HandheldFriendly" content="True" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="<%= base_title(yield(:title)) %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= root_url %>assets/logo.png" />
  <meta property="og:site_name" content="Sergio Mironescu" />
  <% if @post %>
  <meta property="article:section" content="Article" />
  <meta property="article:published_time" content="<%= @post.created_at %>" />
  <% end %>
  <link rel="canonical" href="<%= request.original_url %>" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- <link rel="apple-touch-icon-precomposed" sizes="144x144" href="apple-touch-icon-144x144-precomposed.png"> -->
  <!-- For iPhone with high-resolution Retina display: -->
  <!-- <link rel="apple-touch-icon-precomposed" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png"> -->
  <!-- For first- and second-generation iPad: -->
  <!-- <link rel="apple-touch-icon-precomposed" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png"> -->
  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png"> -->
  <%= render 'layouts/ie9_fix' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/sidebar' %>
  <main id="main_content">
    <div class="wrapper">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </main>
  <%= javascript_include_tag 'custom', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'google_analytics', 'data-turbolinks-track' => false %>
</body>